# Titles to use for the report.
title: "HiCFlow"
subtitle: "Summary & Statistics"
intro_text: "MultiQC reports for Hi-C Data."
report_header_info:
        - Analyzed by: 'HiCFlow@KAUST'
## Change the output filenames
output_fn_name: mqc_report.html
data_dir_name: mqc_report_data
